Add Ubuntu Mono to Typography Section
freeCodeCamp/design-style-guide pull request #6
Opened 2017-01-08 15:51 UTC by user512

* Add ubuntu_mono.zip to /downloads

closes https://github.com/FreeCodeCamp/design-style-guide/issues/5

2017-01-11 17:01 UTC, ghost requested changes

2017-01-11 17:01 UTC, atjonathan commented on index.html
> +				<p>Free Code Camp uses <a href="https://www.google.com/fonts/specimen/Ubuntu+Mono">Ubuntu Mono</a> in code editor.</p>
```diff
- in code editor.
+ for our code editor.
```

2017-01-11 17:01 UTC, atjonathan commented on index.html
> +				<span class="small"><a href="downloads/ubuntu_mono.zip">Download Ubuntu Mono</a></span>
Can you rename the other items in the downloads folder to use underscores for consistency? For example; `sax_mono.zip`. Thanks 😃

2017-01-16 04:19 UTC, user512 commented
@atjonathan ready to merge?

2017-01-17 08:11 UTC, ghost approved these changes

2017-01-17 08:11 UTC, atjonathan commented
### LGTM 👍 
Thanks @user512 for contributing!

2017-01-17 08:11 UTC, merged

2017-01-18 00:41 UTC, QuincyLarson commented
@user512 thanks!