chore(about): Update to freeCodeCamp
freeCodeCamp/design-style-guide pull request #7
Opened 2017-01-14 06:36 UTC by raisedadead

2017-01-14 21:34 UTC, ghost requested changes

2017-01-14 21:34 UTC, atjonathan commented on index.html
> +							<a href="downloads/freeCodeCamp.jpg" download>JPEG</a> |
While you're at it, can you fix the indentation issues here?

2017-01-15 14:30 UTC, raisedadead commented on index.html
> +							<a href="downloads/freeCodeCamp.jpg" download>JPEG</a> |
Will make a separate PR?

2017-01-16 21:40 UTC, systimotic approved these changes
LGTM 👍
@atjonathan can you merge?

2017-01-16 22:52 UTC, atjonathan commented on index.html
> +							<a href="downloads/freeCodeCamp.jpg" download>JPEG</a> |
Sure

2017-01-17 08:11 UTC, ghost approved these changes

2017-01-17 08:11 UTC, atjonathan commented
Thanks @raisedadead 🎉 👍

2017-01-17 08:11 UTC, merged